export const Colors = {
  light: {
    background: '#F9EEDB',
    gridBorder: '#A97B50',
    gridBackground: '#F9EEDB',
    cellEmpty: '#e5e5e5',
    cellOccupied: '#4ECDC4',
    cellPreview: '#FFD93D',
    scoreGold: '#6EEB83',
    scoreBlue: '#00D9FF',
    scoreGreen: '#34C759',
    buttonBg: '#7ED957',
    buttonText: '#fff',
    modalBg: 'rgba(0, 0, 0, 0.95)',
    modalContentBg: '#fff',
    modalBorder: '#FFD93D',
    modalTitle: '#A97B50',
    modalScore: '#FFD93D',
    modalRecord: '#00D9FF',
    fontBlack: '#4a473bff',
    fontBlue: '#007AFF',
    fontGreen: '#34C759',
    fontGray: '#999',
    textDark: '#222',
    shadowGold: '#FFD93D',
    shadowCyan: '#4ECDC4',
    white: '#FFF',
    black: '#000',
    optionBg: '#F3E5C0',
  },
  dark: {
    background: '#0a0a0a',
    gridBorder: '#676666ff',
    gridBackground: '#1a1a1a',
    cellEmpty: '#2a2a2a',
    cellOccupied: '#4ECDC4',
    cellPreview: '#FFD93D',
    scoreGold: '#FFD93D',
    scoreBlue: '#00D9FF',
    scoreGreen: '#34C759',
    buttonBg: '#4ECDC4',
    buttonText: '#fff',
    modalBg: 'rgba(0, 0, 0, 0.95)',
    modalContentBg: '#1a1a1a',
    modalBorder: '#FFD93D',
    modalTitle: '#FF3B77',
    modalScore: '#FFD93D',
    modalRecord: '#00D9FF',
    fontBlack: '#FFD93D',
    fontBlue: '#007AFF',
    fontGreen: '#34C759',
    fontGray: '#999',
    textDark: '#fff',
    shadowGold: '#FFD93D',
    shadowCyan: '#4ECDC4',
    white: '#FFF',
    black: '#000',
    optionBg: '#222',
  },
};
